using Pkg

Pkg.add("PyCall")
Pkg.add("NearestNeighbors")
Pkg.add("Distances")
Pkg.add("Statistics")
Pkg.add("ImageFiltering")
Pkg.add("Colors")
Pkg.add("StatsBase")
Pkg.add("StaticArrays")
Pkg.add("Distributions")
Pkg.add("Images")
Pkg.add("TimerOutputs")
Pkg.add("DataStructures")
Pkg.add("Caesar")
Pkg.add("RoMEPlotting")
Pkg.add("Gadfly")
Pkg.update()